### ISSUE TITLE
Modulation of StyleGAN-T is quite strange

### ISSUE THREAD

**Issue by thuanz123** [autonomousvision/stylegan-t#1]
The mechanism for modulation in figure 3b is quite strange. Based on the below figure, I guess that the modulation style s multiply to the feature output from previous block then multiply to the weight and demodulate like in stylegan2?

![image](https://user-images.githubusercontent.com/32274287/217178503-f52389ed-9e80-496e-89c5-3dcb12e112a8.png)

**Comment by listener17** [comment]
Is this work (StyleGAN-T) based on StyleGAN 1 or 2 or 3?

**Comment by xl-sr** [comment]
Demodulation works as in StyleGAN2 :)
