### ISSUE TITLE
What is the expected date of code release?

### ISSUE THREAD

**Issue by piotr-komorowski** [autonomousvision/stylegan-t#3]

**Comment by WyattAutomation** [comment]
I hope this doesn't stay unreleased, it's an incredible milestone for interactive visualization.

**Comment by Dandelionym** [comment]
One more push for the release.

**Comment by xl-sr** [comment]
I won't stay unreleased, I aiming for end of March :)

**Comment by WyattAutomation** [comment]
I love Stable Diffusion but I can't imagine I am the only one that has been trying to do what you've accomplished here.  I can't thank you enough for being willing to both accomplish this and share it!  Looking forward to diving in to this.

**Comment by andzejsp** [comment]
Cant wait for others to work on some sort user friendly UI

**Comment by WyattAutomation** [comment]
> Cant wait for others to work on some sort user friendly UI

like this?  ;)
https://youtu.be/FJla6yEXLcY

**Comment by zhouwy19** [comment]
Waiting!

**Comment by shangdibufashi** [comment]
One more push for the release.

**Comment by andzejsp** [comment]
![image](https://user-images.githubusercontent.com/80409979/224491814-23d612f3-2fdf-4460-a1b9-a6ae94ddf470.png)

**Comment by FrancescoSaverioZuppichini** [comment]
come onnnnnnnnn 🚀
