### ISSUE TITLE
Compare with ProjectGAN code

### ISSUE THREAD

**Issue by lcxsnow** [autonomousvision/stylegan-t#9]
In the Launch processes of calc_metrics.py.

I saw that it does the if else to check the num__gpus in ProjectGAN but it doesn't in StyleGAN-T?
Does that mean this can't run in one gpu? or this will not run as efficient as ProjectGAN's?

**Comment by xl-sr** [comment]
It works with a single GPU or several. ```--num-gpus``` is now deprecated and handled automatically.
